import {PTRuntime} from './pt-runtime.js';
const [exact,body,bind,headData]=await Promise.all(['exact.json','body.json','bind.json','head.json'].map(x=>fetch(x+'?v=12-head',{cache:'no-store'}).then(r=>r.json())));
// Use only the original high-detail Knight head; M/L are LOD copies.
const head={objects:headData.objects.filter(o=>o.name==='MmhA03d_H')};
const c=document.querySelector('#c'),ctx=c.getContext('2d'),stat=document.querySelector('#stat');
const runtimes=Object.fromEntries(Object.entries(exact.sets).map(([k,bones])=>[k,new PTRuntime({bones})]));
let mode='idle',frame=exact.ranges.idle[0],last=performance.now(),yaw=-.55,pitch=.08,drag=false,lx=0,ly=0,px=0,pz=0,attack=false,zoom=1;
const ZOOM_MIN=.42,ZOOM_MAX=1.85;
function setZoom(z){zoom=Math.max(ZOOM_MIN,Math.min(ZOOM_MAX,z))}
c.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.00115))},{passive:false});
const keys=new Set();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();startAttack()}});addEventListener('keyup',e=>keys.delete(e.code));
function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function tr(v,m){return[v[0]*m[0]+v[1]*m[4]+v[2]*m[8]+m[12],v[0]*m[1]+v[1]*m[5]+v[2]*m[9]+m[13],v[0]*m[2]+v[1]*m[6]+v[2]*m[10]+m[14]]}
function cam(p){let[x,y,z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw);[x,z]=[x*cy-z*sy,x*sy+z*cy];const cp=Math.cos(pitch),sp=Math.sin(pitch);[y,z]=[y*cp-z*sp,y*sp+z*cp];return[x,y,z]}
function startAttack(){if(attack)return;attack=true;mode='attack';frame=exact.ranges.attack[0]} const atk=document.querySelector('#atk');if(atk)atk.onpointerdown=e=>{e.preventDefault();startAttack()};const skill=document.querySelector('#skill');if(skill)skill.onpointerdown=e=>{e.preventDefault();startAttack()};
let joy={x:0,y:0,id:null};const jb=document.querySelector('#joy'),knob=document.querySelector('#knob');function joyMove(e){const r=jb.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),d=Math.hypot(dx,dy)||1,m=Math.min(1,d/(r.width*.38));joy.x=dx/d*m;joy.y=dy/d*m;knob.style.transform=`translate(${joy.x*34}px,${joy.y*34}px)`}if(jb){jb.onpointerdown=e=>{joy.id=e.pointerId;jb.setPointerCapture(e.pointerId);joyMove(e)};jb.onpointermove=e=>{if(e.pointerId===joy.id)joyMove(e)};jb.onpointerup=jb.onpointercancel=e=>{if(e.pointerId===joy.id){joy={x:0,y:0,id:null};knob.style.transform=''}}}
const camTouches=new Map();let pinchDist=0,pinchZoom=1;
c.onpointerdown=e=>{camTouches.set(e.pointerId,{x:e.clientX,y:e.clientY});c.setPointerCapture(e.pointerId);if(camTouches.size===1){drag=true;lx=e.clientX;ly=e.clientY}else if(camTouches.size===2){drag=false;const a=[...camTouches.values()];pinchDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);pinchZoom=zoom}};
c.onpointermove=e=>{if(!camTouches.has(e.pointerId))return;camTouches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(camTouches.size===2){const a=[...camTouches.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinchDist>8)setZoom(pinchZoom*d/pinchDist);return}if(!drag)return;yaw+=(e.clientX-lx)*.008;pitch=Math.max(-.8,Math.min(.8,pitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY};
function camUp(e){camTouches.delete(e.pointerId);if(camTouches.size===1){const a=[...camTouches.values()][0];drag=true;lx=a.x;ly=a.y}else drag=false}
c.onpointerup=camUp;c.onpointercancel=camUp;
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joy.x,mz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+joy.y,moving=Math.hypot(mx,mz)>.15;if(moving&&!attack){let d=Math.hypot(mx,mz);mx/=d;mz/=d;px+=mx*dt*2;pz+=mz*dt*2}let wanted=attack?'attack':moving?'run':'idle';if(wanted!==mode&&!attack){mode=wanted;frame=exact.ranges[mode][0]}const range=exact.ranges[mode],rt=runtimes[mode];frame+=dt*160*24;if(frame>=range[1]){if(attack){attack=false;mode=moving?'run':'idle';frame=exact.ranges[mode][0]}else frame=range[0]+(frame-range[0])%(range[1]-range[0])}
const pose=runtimes[mode].pose(frame),tris=[];let minY=1e9,maxY=-1e9;for(const o of [...body.objects,...head.objects]){const vv=o.vertices.map((v,i)=>{const pm=pose.get(o.physique[i]),pt=pm?tr(v,pm):v,w=[pt[0],pt[2],pt[1]];minY=Math.min(minY,w[1]);maxY=Math.max(maxY,w[1]);return cam(w)});for(const f of o.faces){const a=vv[f[0]],b=vv[f[1]],d=vv[f[2]];if(a&&b&&d)tris.push({p:[a,b,d],z:(a[2]+b[2]+d[2])/3})}}tris.sort((a,b)=>a.z-b.z);ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#1a1d22';ctx.fillRect(0,innerHeight*.82,innerWidth,innerHeight*.18);const h=Math.max(1,maxY-minY),baseSc=Math.min(innerHeight*.72/h,55),sc=baseSc*zoom,ox=innerWidth/2,oy=innerHeight*.82;ctx.lineWidth=.55;for(const t of tris){const shade=Math.max(58,Math.min(178,118-t.z*1.8));ctx.fillStyle=`rgb(${Math.round(shade*.72)},${Math.round(shade*.78)},${Math.round(shade*.88)})`;ctx.strokeStyle='rgba(225,232,245,.24)';ctx.beginPath();ctx.moveTo(ox+t.p[0][0]*sc,oy-t.p[0][1]*sc);ctx.lineTo(ox+t.p[1][0]*sc,oy-t.p[1][1]*sc);ctx.lineTo(ox+t.p[2][0]*sc,oy-t.p[2][1]*sc);ctx.closePath();ctx.fill();ctx.stroke()}stat.textContent=`TEST 12 HEAD + PT ZOOM • ${mode.toUpperCase()} • zoom ${zoom.toFixed(2)}x • frame ${Math.floor(frame/160)}`;requestAnimationFrame(loop)}requestAnimationFrame(loop);
if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.unregister())));caches.keys().then(ks=>Promise.all(ks.map(k=>caches.delete(k))))}
