const $=x=>document.getElementById(x);
const monsters=["SLIME","GOBLIN","WILD BOAR","FOREST BAT"];
const icons=["🟢","👺","🐗","🦇"];
const gear=[["Rusty Sword","⚔️","weapon",5],["Leather Armor","🥋","armor",3],["Iron Sword","🗡️","weapon",9],["Knight Armor","🛡️","armor",7],["Ruby Ring","💍","crit",3]];
let S=JSON.parse(localStorage.getItem("idleRpgSave")||"null")||{level:1,xp:0,gold:0,gems:25,stage:1,stageKills:0,kills:0,atk:18,def:5,maxhp:120,hp:120,inventory:[],equipped:{},last:Date.now(),quest:false};
let M={hp:50,max:50,name:"SLIME",boss:false}, cooldown=0, timer=0;
function need(){return 80+S.level*20}
function save(){S.last=Date.now();localStorage.setItem("idleRpgSave",JSON.stringify(S))}
function spawn(boss=false){let n=boss?"FOREST GUARDIAN":monsters[Math.floor(Math.random()*monsters.length)];let base=45+S.stage*18;M={name:n,max:boss?base*5:base,hp:boss?base*5:base,boss};$("monsterName").textContent=n;$("monster").firstChild.nodeValue=boss?"🐲":icons[Math.floor(Math.random()*icons.length)];draw()}
function damage(mult=1){let crit=Math.random()<.08;let d=Math.round(S.atk*mult*(.85+Math.random()*.3)*(crit?1.7:1));M.hp-=d;$("player").classList.add("attack");$("monster").classList.add("hit");$("fx").innerHTML=`<b style="position:absolute;left:62%;top:42%;font-size:28px;color:${crit?"#ffd85c":"white"}">-${d}${crit?" CRIT!":""}</b>`;setTimeout(()=>{$("player").classList.remove("attack");$("monster").classList.remove("hit");$("fx").innerHTML=""},150);if(M.hp<=0)kill();draw()}
function kill(){let boss=M.boss,g=Math.floor(5+Math.random()*6)+S.stage*2;S.gold+=boss?g*10:g;let gain=boss?50:12;S.xp+=gain;S.kills++;S.stageKills++;if(Math.random()<.23){let x=gear[Math.floor(Math.random()*gear.length)];S.inventory.push({name:x[0],icon:x[1],type:x[2],val:x[3]+Math.floor(S.stage/2)})}while(S.xp>=need()){S.xp-=need();S.level++;S.atk+=3;S.def+=1;S.maxhp+=12;S.hp=S.maxhp}if(boss){S.stage++;S.stageKills=0}if(S.stageKills>=10){$("boss").disabled=false;spawn(false)}else spawn(false);save();render()}
function render(){ $("gold").textContent=S.gold.toLocaleString();$("gems").textContent=S.gems;$("lvl").textContent="Lv. "+S.level;$("xp").textContent=S.xp;$("xpneed").textContent=need();$("xpbar").style.width=(S.xp/need()*100)+"%";$("atk").textContent=S.atk;$("def").textContent=S.def;$("hpstat").textContent=S.maxhp;$("stage").textContent=`1-${S.stage} GREEN FOREST`;$("progress").textContent=`${Math.min(S.stageKills,10)} / 10`;$("kills").textContent=Math.min(S.kills,50);$("questbar").style.width=Math.min(100,S.kills/50*100)+"%";$("claim").disabled=S.kills<50||S.quest;$("mlevel").textContent="Lv. "+S.stage;$("reward").textContent=(5+S.stage*2)+"–"+(10+S.stage*2)+" Gold";draw();showTab(document.querySelector(".tabs .active").dataset.tab)}
function draw(){$("mhp").style.width=Math.max(0,M.hp/M.max*100)+"%";$("php").style.width="100%"}
function showTab(t){let c=$("content");if(t==="inventory"){c.innerHTML='<h3>INVENTORY</h3><div class="items">'+(S.inventory.length?S.inventory.map((x,i)=>`<div class="item"><div style="font-size:30px">${x.icon}</div><b>${x.name}</b><small>+${x.val} ${x.type.toUpperCase()}</small><button onclick="equip(${i})">EQUIP</button></div>`).join(""):"Defeat monsters to find equipment.")+"</div>"}else if(t==="upgrade"){c.innerHTML=`<h3>BLACKSMITH</h3><p>Upgrade your base weapon damage. Cost increases each time.</p><button onclick="upgrade()">⚒ UPGRADE ATK +2 • ${50+S.atk*3} 🪙</button>`}else if(t==="map"){c.innerHTML='<h3>WORLD MAP</h3><div class="maps"><div class="map"><b>🌲 Green Forest</b><small>Current Area</small></div><div class="map locked">🏜 Dry Desert<br><small>Coming next</small></div><div class="map locked">🏰 Dark Dungeon<br><small>Coming next</small></div><div class="map locked">❄ Frozen Land<br><small>Coming next</small></div></div>'}else c.innerHTML="<h3>BUILD 1</h3><p>Auto combat, leveling, stages, boss battles, item drops, inventory/equipment, upgrades, quests, local save and offline Gold are working. More classes, skills and maps can be added next.</p>"}
window.equip=i=>{let x=S.inventory[i];if(!x)return;if(x.type==="weapon")S.atk+=x.val;if(x.type==="armor"){S.def+=x.val;S.maxhp+=x.val*3}S.inventory.splice(i,1);save();render()}
window.upgrade=()=>{let cost=50+S.atk*3;if(S.gold>=cost){S.gold-=cost;S.atk+=2;save();render()}}
$("skill").onclick=()=>{if(cooldown<=0){damage(2.8);cooldown=5}};
$("boss").onclick=()=>{$("boss").disabled=true;spawn(true)};
$("claim").onclick=()=>{if(S.kills>=50&&!S.quest){S.gold+=500;S.quest=true;save();render()}};
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");showTab(b.dataset.tab)});
let away=Math.min(8*3600,Math.floor((Date.now()-S.last)/1000));if(away>60){let bonus=Math.floor(away/30)*(3+S.stage);S.gold+=bonus;setTimeout(()=>alert(`Welcome back! Offline reward: ${bonus} Gold`),400)}
spawn();render();setInterval(()=>{timer++;if(timer%2===0)damage(1);if(cooldown>0){cooldown--;$("cd").textContent=cooldown+"s"}else $("cd").textContent="READY";save()},1000);