import {PTRuntime} from './pt-runtime.js';
const [clips,body,bind]=await Promise.all(['clips.json','body.json','bind.json'].map(x=>fetch(x).then(r=>r.json())));
const ids=Object.keys(clips.segments), c=document.querySelector('#c'),ctx=c.getContext('2d'),stat=document.querySelector('#stat');
const idleSel=document.querySelector('#idleSeg'),runSel=document.querySelector('#runSeg'),atkSel=document.querySelector('#atkSeg');
for(const s of [idleSel,runSel,atkSel]) for(const id of ids){const o=document.createElement('option');o.value=id;o.textContent=id;s.append(o)}
idleSel.value=ids.includes('1')?'1':ids[0];runSel.value=ids.includes('4')?'4':ids[Math.min(1,ids.length-1)];atkSel.value=ids.includes('10')?'10':ids[Math.min(2,ids.length-1)];
const runtimes={}; function RT(id){return runtimes[id]??=(s=>new PTRuntime({bones:s.bones.map(b=>({...b,frames:[b.frame]}))}))(clips.segments[id])}
let mode='idle',frame=clips.segments[idleSel.value].start,last=performance.now(),yaw=-.55,pitch=.08,drag=false,lx=0,ly=0,px=0,pz=0,attack=false;
const keys=new Set(); addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();startAttack()}});addEventListener('keyup',e=>keys.delete(e.code));
function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function tr(v,m){return [v[0]*m[0]+v[1]*m[4]+v[2]*m[8]+m[12],v[0]*m[1]+v[1]*m[5]+v[2]*m[9]+m[13],v[0]*m[2]+v[1]*m[6]+v[2]*m[10]+m[14]]}
function cam(p){let[x,y,z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw);[x,z]=[x*cy-z*sy,x*sy+z*cy];const cp=Math.cos(pitch),sp=Math.sin(pitch);[y,z]=[y*cp-z*sp,y*sp+z*cp];return[x,y,z]}
function startAttack(){if(attack)return;attack=true;mode='attack';frame=clips.segments[atkSel.value].start} document.querySelector('#atk').onpointerdown=e=>{e.preventDefault();startAttack()};document.querySelector('#skill').onpointerdown=e=>{e.preventDefault();startAttack()};
let joy={x:0,y:0,id:null};const jb=document.querySelector('#joy'),knob=document.querySelector('#knob');function joyMove(e){const r=jb.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),d=Math.hypot(dx,dy)||1,m=Math.min(1,d/(r.width*.38));joy.x=dx/d*m;joy.y=dy/d*m;knob.style.transform=`translate(${joy.x*34}px,${joy.y*34}px)`}jb.onpointerdown=e=>{joy.id=e.pointerId;jb.setPointerCapture(e.pointerId);joyMove(e)};jb.onpointermove=e=>{if(e.pointerId===joy.id)joyMove(e)};jb.onpointerup=jb.onpointercancel=e=>{if(e.pointerId===joy.id){joy={x:0,y:0,id:null};knob.style.transform=''}};
c.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-lx)*.008;pitch=Math.max(-.8,Math.min(.8,pitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY};c.onpointerup=c.onpointercancel=()=>drag=false;
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;let mx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x;let mz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.y;let moving=Math.hypot(mx,mz)>.15;if(moving&&!attack){let d=Math.hypot(mx,mz);mx/=d;mz/=d;px+=mx*dt*2;pz+=mz*dt*2}
 let wanted=attack?'attack':moving?'run':'idle';if(wanted!==mode&&!attack){mode=wanted;let id=mode==='run'?runSel.value:idleSel.value;frame=clips.segments[id].start}let id=mode==='attack'?atkSel.value:mode==='run'?runSel.value:idleSel.value,s=clips.segments[id],rt=RT(id);frame+=dt*160*9.6;if(frame>=s.end){if(attack){attack=false;mode=moving?'run':'idle';id=mode==='run'?runSel.value:idleSel.value;s=clips.segments[id];frame=s.start}else frame=s.start+(frame-s.start)%(s.end-s.start)}
 const pose=rt.pose(frame),tris=[];let minY=1e9,maxY=-1e9;for(const o of body.objects){const vv=o.vertices.map((v,i)=>{const bn=o.physique[i],pm=pose.get(bn),bi=bind[bn]?.inv;const pt=pm?tr(v,pm):v; /* PT WorldForm stores transformed Z as world Y, and transformed Y as world Z */ const w=[pt[0],pt[2],pt[1]];minY=Math.min(minY,w[1]);maxY=Math.max(maxY,w[1]);return cam(w)});for(const f of o.faces){const a=vv[f[0]],b=vv[f[1]],d=vv[f[2]];if(a&&b&&d)tris.push({p:[a,b,d],z:(a[2]+b[2]+d[2])/3})}}tris.sort((a,b)=>a.z-b.z);ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#1a1d22';ctx.fillRect(0,innerHeight*.82,innerWidth,innerHeight*.18);const h=Math.max(1,maxY-minY),sc=Math.min(innerHeight*.72/h,55),ox=innerWidth/2,oy=innerHeight*.82;ctx.lineWidth=.55;for(const t of tris){const z=t.z;const shade=Math.max(58,Math.min(178,118-z*1.8));ctx.fillStyle=`rgb(${Math.round(shade*.72)},${Math.round(shade*.78)},${Math.round(shade*.88)})`;ctx.strokeStyle='rgba(225,232,245,.24)';ctx.beginPath();ctx.moveTo(ox+t.p[0][0]*sc,oy-t.p[0][1]*sc);ctx.lineTo(ox+t.p[1][0]*sc,oy-t.p[1][1]*sc);ctx.lineTo(ox+t.p[2][0]*sc,oy-t.p[2][1]*sc);ctx.closePath();ctx.fill();ctx.stroke()}stat.textContent=`${mode.toUpperCase()} • segment ${id} • frame ${Math.floor(frame/160)} • pos ${px.toFixed(1)}, ${pz.toFixed(1)}`;requestAnimationFrame(loop)}requestAnimationFrame(loop);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
